spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/SsaMuSo?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  logging:
    level:
      org.hibernate.SQL: debug


cloud:
  aws:
    credentials:
      accessKey: AKIAUX4ZADFPUKVDE4TY
      secretKey: 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
    s3:
      bucket: prj-novel
    region:
      static: ap-northeast-2
    stack:
      auto: false